function SetSpeedGlobal(){
	pl <- null;
	while(null != (pl = Entities.FindByClassname(pl, "player"))){
	if(pl.GetMaxHealth() == 100){
			EntFire("speedMod", "ModifySpeed", "1", 0.0, pl);
			EntFireByHandle(pl, "AddOutput", "gravity 1", 0.0, null, null);
		} else if(pl.GetMaxHealth() == 275){
			EntFire("speedMod", "ModifySpeed", "0.88", 0.0, pl); //0.86
			EntFireByHandle(pl, "AddOutput", "gravity 1.08", 0.0, null, null);
		} else if(pl.GetMaxHealth() == 99999){
			EntFire("speedMod", "ModifySpeed", "0.70", 0.0, pl);
			EntFireByHandle(pl, "AddOutput", "gravity 2", 0.0, null, null);
		} else if(pl.GetMaxHealth() == 101){
			EntFire("speedMod", "ModifySpeed", "1.5", 0.0, pl);
		} else if(pl.GetMaxHealth() == 200){
			EntFire("speedMod", "ModifySpeed", "1", 0.0, pl);
		} else if(pl.GetMaxHealth() == 125){
			EntFire("speedMod", "ModifySpeed", "1", 0.0, pl);
		} else if(pl.GetMaxHealth() == 60000){
			EntFire("speedMod", "ModifySpeed", "3", 0.0, pl);
		} else if(pl.GetMaxHealth() == 9000){
			EntFire("speedMod", "ModifySpeed", "1.25", 0.0, pl);
		} else if(pl.GetMaxHealth() == 100000){
			EntFire("speedMod", "ModifySpeed", "0.9", 0.0, pl);
		} else if(pl.GetMaxHealth() == 70000){
			EntFire("speedMod", "ModifySpeed", "1", 0.0, pl);
		} else if(pl.GetMaxHealth() == 71000){
			EntFire("speedMod", "ModifySpeed", "1.35", 0.0, pl);
			EntFireByHandle(pl, "AddOutput", "gravity 0.8", 0.0, null, null);
		}
	}
}

function SetSpeedBalrogSword(){
	EntFire("speedMod", "ModifySpeed", "0", 0.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.70", 3.00, activator);
}


function SetSpeedBalrogRoar(){
	EntFire("speedMod", "ModifySpeed", "0", 0.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.70", 6.00, activator);
}

function SetSpeedGandalfYSNP(){
	EntFire("speedMod", "ModifySpeed", "0", 0.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.95, activator);
	EntFire("speedMod", "ModifySpeed", "1", 5.00, activator);
}

function SetSpeedGandalfLight(){
	EntFire("speedMod", "ModifySpeed", "0.7", 0.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 0.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 1.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 1.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 1.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 2.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 2.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 2.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 3.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 3.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 3.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 4.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 4.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 4.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 5.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 5.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 5.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 6.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 6.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 6.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 7.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 7.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 7.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 8.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 8.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 8.95, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 9.00, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.05, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.10, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.15, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.20, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.25, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.30, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.35, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.40, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.45, activator);
	EntFire("speedMod", "ModifySpeed", "0.7", 9.50, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.55, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.60, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.65, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.70, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.75, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.80, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.85, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.90, activator);
	//EntFire("speedMod", "ModifySpeed", "0.7", 9.95, activator);
	EntFire("speedMod", "ModifySpeed", "1", 10.00, activator);
}

function SetSpeedWKHeavySword(){
	EntFire("speedMod", "ModifySpeed", "0", 0.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "1", 1.50, activator);
}

function SetSpeedWKGuard(){
	EntFire("speedMod", "ModifySpeed", "0", 0.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.95, activator);
	EntFire("speedMod", "ModifySpeed", "1", 2.00, activator);
}


function SetSpeedWKNuke(){
	EntFire("speedMod", "ModifySpeed", "0", 0.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 0.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 1.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 2.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 3.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 4.95, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.00, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.05, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.10, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.15, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.20, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.25, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.30, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.35, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.40, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.45, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.50, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.55, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.60, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.65, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.70, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.75, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.80, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.85, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.90, activator);
	EntFire("speedMod", "ModifySpeed", "0", 5.95, activator);
	EntFire("speedMod", "ModifySpeed", "1", 6.00, activator);
}


function SetSpeedyBalrogPlayers(){
	if(activator.GetMaxHealth() == 100){
		EntFire("speedMod", "ModifySpeed", "1.5", 0.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 0.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 1.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 2.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 3.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 4.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 5.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 6.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 7.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 8.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.00, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.05, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.10, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.15, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.20, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.25, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.30, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.35, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.40, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.45, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.50, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.55, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.60, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.65, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.70, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.75, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.80, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.85, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.90, activator);
		EntFire("speedMod", "ModifySpeed", "1.5", 9.95, activator);
		EntFire("speedMod", "ModifySpeed", "1.15", 10.00, activator);
		EntFire("!activator", "AddOutput", "health 10000", 0.00, activator);
		EntFire("!activator", "Color", "255 0 0", 0.00, activator);
		EntFire("!activator", "Color", "255 0 0", 0.50, activator);
		EntFire("!activator", "Color", "255 0 0", 1.00, activator);
		EntFire("!activator", "Color", "255 0 0", 1.50, activator);
		EntFire("!activator", "Color", "255 0 0", 2.00, activator);
		EntFire("!activator", "Color", "255 0 0", 2.50, activator);
		EntFire("!activator", "Color", "255 0 0", 3.00, activator);
		EntFire("!activator", "Color", "255 0 0", 3.50, activator);
		EntFire("!activator", "Color", "255 0 0", 4.00, activator);
		EntFire("!activator", "Color", "255 0 0", 4.50, activator);
		EntFire("!activator", "Color", "255 0 0", 5.00, activator);
		EntFire("!activator", "Color", "255 0 0", 5.50, activator);
		EntFire("!activator", "Color", "255 0 0", 6.00, activator);
		EntFire("!activator", "Color", "255 0 0", 6.50, activator);
		EntFire("!activator", "Color", "255 0 0", 7.00, activator);
		EntFire("!activator", "Color", "255 0 0", 7.50, activator);
		EntFire("!activator", "Color", "255 0 0", 8.00, activator);
		EntFire("!activator", "Color", "255 0 0", 8.50, activator);
		EntFire("!activator", "Color", "255 0 0", 9.00, activator);
		EntFire("!activator", "Color", "255 0 0", 9.50, activator);
		EntFire("!activator", "Color", "255 255 255", 10.00, activator);
	}
}


function KillGandalf(){
	pl <- null;
	while(null != (pl = Entities.FindByClassname(pl, "player"))){
	if(pl.GetMaxHealth() == 70000){
		EntFireByHandle(pl, "SetHealth", "-999999999", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "max_health 100", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "rendermode 0", 0.0, null, null);
		EntFireByHandle(pl, "SetDamageFilter", "", 0.0, null, null);
	}
	}
}

function KillBalrog(){
	pl <- null;
	while(null != (pl = Entities.FindByClassname(pl, "player"))){
	if(pl.GetMaxHealth() == 99999){
		EntFireByHandle(pl, "SetHealth", "-999999999", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "max_health 100", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "rendermode 0", 0.0, null, null);
		EntFireByHandle(pl, "SetDamageFilter", "", 0.0, null, null);
	}
	}
}

function KillWhiteKnight(){
	pl <- null;
	while(null != (pl = Entities.FindByClassname(pl, "player"))){
	if(pl.GetMaxHealth() == 72000){
		EntFireByHandle(pl, "SetHealth", "-999999999", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "max_health 100", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "rendermode 0", 0.0, null, null);
		EntFireByHandle(pl, "SetDamageFilter", "", 0.0, null, null);
	}
	}
}

function KillTroll(){
	pl <- null;
	while(null != (pl = Entities.FindByClassname(pl, "player"))){
	if(pl.GetMaxHealth() == 100001){
		EntFireByHandle(pl, "SetHealth", "-999999999", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "max_health 100", 0.0, null, null);
		EntFireByHandle(pl, "AddOutput", "rendermode 0", 0.0, null, null);
		EntFireByHandle(pl, "SetDamageFilter", "", 0.0, null, null);
	}
	}
}

function CheckIfNazgul(){
	if(activator.GetMaxHealth() == 60000){
		EntFireByHandle(activator, "SetHealth", "-999999", 0.10, null, null);
		EntFireByHandle(activator, "AddOutput", "max_health 100", 0.0, null, null);
		EntFireByHandle(activator, "AddOutput", "rendermode 0", 0.0, null, null);
		EntFireByHandle(activator, "SetDamageFilter", "", 0.0, null, null);
	}
}

function PushIfNazgul(){
	if(activator.GetMaxHealth() == 60000){
		EntFireByHandle(activator, "AddOutput", "basevelocity 512 0 0", 0.0, null, null);
	}
}